### ISSUE TITLE
App Crash on taking Image.

### ISSUE THREAD

**Issue by JoysonF** [pinguo-yuyidong/Camera2#10]
Whenever i try taking an image on MOTO X Play , by changing the flash mode the app crashes.
**Following is the crash Log:**
FATAL EXCEPTION: main
                                                                       Process: us.yydcdut.androidltest, PID: 7764
                                                                       java.lang.IllegalArgumentException: Bad argument passed to camera service
                                                                           at android.hardware.camera2.utils.CameraBinderDecorator.throwOnError(CameraBinderDecorator.java:114)
                                                                           at android.hardware.camera2.utils.CameraBinderDecorator$CameraBinderDecoratorListener.onAfterInvocation(CameraBinderDecorator.java:73)
                                                                           at android.hardware.camera2.utils.Decorator.invoke(Decorator.java:81)
                                                                           at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                           at $Proxy1.createDefaultRequest(Unknown Source)
                                                                           at android.hardware.camera2.impl.CameraDeviceImpl.createCaptureRequest(CameraDeviceImpl.java:628)
                                                                           at us.yydcdut.androidltest.ui.DisplayFragment.takePicture(DisplayFragment.java:563)
                                                                           at us.yydcdut.androidltest.ui.DisplayFragment.access$400(DisplayFragment.java:85)
                                                                           at us.yydcdut.androidltest.ui.DisplayFragment$2.onTouch(DisplayFragment.java:438)
                                                                           at android.view.View.dispatchTouchEvent(View.java:9299)

**Comment by fyv5** [comment]
I find the word“CameraDevice.TEMPLATE_ZERO_SHUTTER_LAG” is wrong.

**Comment by JoysonF** [comment]
I haven't made any changes to the project , just compiled and ran the project. However its only crashing on Moto devices when i click on capture image icon. What should have been the value instead of CameraDevice.TEMPLATE_ZERO_SHUTTER_LAG ?

**Comment by bonjourss** [comment]
@JoysonF CameraDevice.TEMPLATE_STILL_CAPTURE
